name: "variable access"
on: push
evn: 
    name: "Darshan"
jobs:
  variable-access:
      run-on: ubuntu-latest
      evn: 
        lastname: "H M"
      steps:
        - name: step variable access
          evn: 
            age: 10
        - name: run code
          runs: |
            echo "my name is ${{evn.name}} ${{evn.lastname} and age is ${{evn.age}}}"