name: "variable access"
on: push
env: 
  name: "Darshan"
jobs:
  variable-access:
      runs-on: ubuntu-latest
      env: 
        lastname: "H M"
      steps:
        - name: step variable access
          env: 
            age: 10
          run: |
            echo "my name is ${{env.name}} ${{env.lastname}} and age is ${{env.age}}} and my pin is ${{secrets.pin}}"